name: Issue comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "$GITHUB_CONTEXT"
        env:
          NUMBER: ${{ toJson(github) }}
